# Generated by Django 4.0.4 on 2022-05-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaHortifruti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=96)),
                ('tipo', models.CharField(choices=[('Segunda', 'Segunda'), ('Quarta', 'Quarta'), ('Sexta', 'Sexta')], max_length=32)),
                ('data_final', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemHortifruti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('descricao', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoHortifruti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(default='', max_length=96)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hortifruti.agendahortifruti')),
            ],
        ),
        migrations.CreateModel(
            name='QuantidadeItemHortifruti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='', max_length=96)),
                ('quantidadeRequisitada', models.PositiveIntegerField(default=0)),
                ('quantidadeAdquirida', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hortifruti.itemhortifruti')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hortifruti.pedidohortifruti')),
            ],
        ),
    ]
