# Generated by Django 4.0.4 on 2022-05-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaAbastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=96)),
                ('tipo', models.CharField(choices=[('Semanal', 'Semanal'), ('Quinzenal', 'Quinzenal'), ('Mensal', 'Mensal')], max_length=32)),
                ('data_cadastro', models.DateField(auto_now=True)),
                ('data_final', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaAbastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAbastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('descricao', models.CharField(max_length=32, unique=True)),
                ('tipo', models.CharField(choices=[('Semanal', 'Semanal'), ('Quinzenal', 'Quinzenal'), ('Mensal', 'Mensal')], max_length=32)),
                ('data_cadastro', models.DateField(auto_now=True)),
                ('data_modificado', models.DateField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.categoriaabastecimento')),
                ('empresas', models.ManyToManyField(to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoAbastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(default='', max_length=96)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.agendaabastecimento')),
            ],
        ),
        migrations.CreateModel(
            name='QuantidadeItemAbastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='', max_length=96)),
                ('habilitado', models.CharField(default='', max_length=2)),
                ('quantidadeRequisitada', models.PositiveIntegerField(default=0)),
                ('quantidadeAdquirida', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.itemabastecimento')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.pedidoabastecimento')),
            ],
        ),
    ]
