# Generated by Django 4.0.4 on 2022-05-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0002_alter_agendaabastecimento_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantidadeitemabastecimento',
            name='quantidadeAcougue',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quantidadeitemabastecimento',
            name='quantidadeLoja',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quantidadeitemabastecimento',
            name='quantidadePadaria',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quantidadeitemabastecimento',
            name='quantidadeVerdura',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
