# Generated by Django 4.0.4 on 2022-05-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0004_quantidadeitemabastecimento_acougue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantidadeitemabastecimento',
            name='acougue',
        ),
        migrations.RemoveField(
            model_name='quantidadeitemabastecimento',
            name='loja',
        ),
        migrations.RemoveField(
            model_name='quantidadeitemabastecimento',
            name='padaria',
        ),
        migrations.RemoveField(
            model_name='quantidadeitemabastecimento',
            name='verdura',
        ),
        migrations.AddField(
            model_name='itemabastecimento',
            name='acougue',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='N', max_length=2),
        ),
        migrations.AddField(
            model_name='itemabastecimento',
            name='loja',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='N', max_length=2),
        ),
        migrations.AddField(
            model_name='itemabastecimento',
            name='padaria',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='N', max_length=2),
        ),
        migrations.AddField(
            model_name='itemabastecimento',
            name='verdura',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='N', max_length=2),
        ),
    ]
