# Generated by Django 4.0.4 on 2022-05-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0006_quantidadeitemabastecimento_acougue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemabastecimento',
            name='situacao',
            field=models.CharField(default='', max_length=32),
        ),
    ]
