# Generated by Django 4.0.4 on 2022-05-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0007_itemabastecimento_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemabastecimento',
            name='descricao',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='itemabastecimento',
            name='situacao',
            field=models.CharField(default='  --//--  ', max_length=32),
        ),
    ]
